/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import javax.swing.JLabel;
import logica.Paciente;

/**
 *
 * @author Usuario
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        //this.setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        
        separador1.setVisible(false);
        separador2.setVisible(false);
        btnLimpiar.setVisible(false);

        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblRaza = new javax.swing.JLabel();
        txtRaza = new javax.swing.JTextField();
        lblDimension = new javax.swing.JLabel();
        select = new javax.swing.JComboBox<>();
        lblNombre = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtNombreDue = new javax.swing.JTextField();
        lblNombreDue = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        separadorNombreDue = new javax.swing.JSeparator();
        separadorNombre = new javax.swing.JSeparator();
        separadorRaza = new javax.swing.JSeparator();
        btnAgregar = new javax.swing.JButton();
        selectCosto = new javax.swing.JComboBox<>();
        lblMotivo = new javax.swing.JLabel();
        validationRaza = new javax.swing.JLabel();
        validationNombre = new javax.swing.JLabel();
        validationNomDue = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblListado = new javax.swing.JLabel();
        lblPacienteDue1 = new javax.swing.JLabel();
        lblPacienteID1 = new javax.swing.JLabel();
        lblPacienteRaza1 = new javax.swing.JLabel();
        lblPacienteTam1 = new javax.swing.JLabel();
        separador1 = new javax.swing.JSeparator();
        lblPacienteDue2 = new javax.swing.JLabel();
        lblPacienteTam2 = new javax.swing.JLabel();
        lblPacienteRaza2 = new javax.swing.JLabel();
        lblPacienteTam3 = new javax.swing.JLabel();
        lblPacienteRaza3 = new javax.swing.JLabel();
        lblPacienteDue3 = new javax.swing.JLabel();
        separador2 = new javax.swing.JSeparator();
        lblPacienteNombre1 = new javax.swing.JLabel();
        lblPacienteNombre2 = new javax.swing.JLabel();
        lblPacienteID2 = new javax.swing.JLabel();
        lblPacienteNombre3 = new javax.swing.JLabel();
        lblPacienteID3 = new javax.swing.JLabel();
        lblCosto3 = new javax.swing.JLabel();
        lblCosto1 = new javax.swing.JLabel();
        lblCosto2 = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        lblTotal3 = new javax.swing.JLabel();
        lblTotal2 = new javax.swing.JLabel();
        lblAumento3 = new javax.swing.JLabel();
        lblAumento1 = new javax.swing.JLabel();
        lblAumento2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(47, 58, 82));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        titulo.setForeground(new java.awt.Color(242, 243, 244));
        titulo.setText("INGRESE LOS DATOS DEL PACIENTE");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtId.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        txtId.setForeground(new java.awt.Color(242, 243, 244));
        txtId.setText("0005");
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtNombre.setBackground(new java.awt.Color(47, 58, 82));
        txtNombre.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(24, 212, 163));
        txtNombre.setBorder(null);
        txtNombre.setCaretColor(new java.awt.Color(24, 212, 163));
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNombre.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, -1));

        lblRaza.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblRaza.setForeground(new java.awt.Color(242, 243, 244));
        lblRaza.setText("Raza");
        jPanel1.add(lblRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtRaza.setBackground(new java.awt.Color(47, 58, 82));
        txtRaza.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        txtRaza.setForeground(new java.awt.Color(24, 212, 163));
        txtRaza.setBorder(null);
        txtRaza.setCaretColor(new java.awt.Color(24, 212, 163));
        txtRaza.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtRaza.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazaActionPerformed(evt);
            }
        });
        jPanel1.add(txtRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 160, -1));

        lblDimension.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblDimension.setForeground(new java.awt.Color(242, 243, 244));
        lblDimension.setText("Tamaño");
        jPanel1.add(lblDimension, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        select.setBackground(new java.awt.Color(34, 44, 66));
        select.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        select.setForeground(new java.awt.Color(24, 212, 163));
        select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pequeño", "mediano", "grande" }));
        select.setName(""); // NOI18N
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        jPanel1.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 160, -1));

        lblNombre.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(242, 243, 244));
        lblNombre.setText("Nombre");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        lblId.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblId.setForeground(new java.awt.Color(242, 243, 244));
        lblId.setText("ID paciente");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtNombreDue.setBackground(new java.awt.Color(47, 58, 82));
        txtNombreDue.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        txtNombreDue.setForeground(new java.awt.Color(24, 212, 163));
        txtNombreDue.setBorder(null);
        txtNombreDue.setCaretColor(new java.awt.Color(24, 212, 163));
        txtNombreDue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNombreDue.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtNombreDue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDueActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 160, 30));

        lblNombreDue.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblNombreDue.setForeground(new java.awt.Color(242, 243, 244));
        lblNombreDue.setText("Nombre del dueño");
        jPanel1.add(lblNombreDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(60, 105, 189));
        btnLimpiar.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(242, 243, 244));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnLimpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar registro");
        btnLimpiar.setBorder(null);
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setDefaultCapable(false);
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnLimpiar_hover.png"))); // NOI18N
        btnLimpiar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnLimpiar.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 140, 30));

        separadorNombreDue.setBackground(new java.awt.Color(24, 212, 163));
        jPanel1.add(separadorNombreDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 160, 10));

        separadorNombre.setBackground(new java.awt.Color(24, 212, 163));
        jPanel1.add(separadorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 160, 10));

        separadorRaza.setBackground(new java.awt.Color(24, 212, 163));
        jPanel1.add(separadorRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 160, 10));

        btnAgregar.setBackground(new java.awt.Color(60, 105, 189));
        btnAgregar.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(242, 243, 244));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnAgregar.png"))); // NOI18N
        btnAgregar.setText("Confirmar");
        btnAgregar.setBorder(null);
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setDefaultCapable(false);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnAgregar_pressed.png"))); // NOI18N
        btnAgregar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnAgregar.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 110, 30));

        selectCosto.setBackground(new java.awt.Color(34, 44, 66));
        selectCosto.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        selectCosto.setForeground(new java.awt.Color(24, 212, 163));
        selectCosto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "consulta", "baño", "corte de pelo" }));
        selectCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCostoActionPerformed(evt);
            }
        });
        jPanel1.add(selectCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 160, -1));

        lblMotivo.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblMotivo.setForeground(new java.awt.Color(242, 243, 244));
        lblMotivo.setText("Motivo");
        jPanel1.add(lblMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        validationRaza.setForeground(new java.awt.Color(239, 48, 56));
        jPanel1.add(validationRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 30, 20));

        validationNombre.setForeground(new java.awt.Color(239, 48, 56));
        jPanel1.add(validationNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 30, 20));

        validationNomDue.setForeground(new java.awt.Color(239, 48, 56));
        jPanel1.add(validationNomDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 30, 20));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vet.png"))); // NOI18N
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 100, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 450));

        jPanel2.setBackground(new java.awt.Color(47, 58, 82));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblListado.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblListado.setForeground(new java.awt.Color(242, 243, 244));
        lblListado.setText("LISTADO DE PACIENTES");
        jPanel2.add(lblListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        lblPacienteDue1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPacienteDue1.setForeground(new java.awt.Color(242, 243, 244));
        jPanel2.add(lblPacienteDue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 200, 20));

        lblPacienteID1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPacienteID1.setForeground(new java.awt.Color(242, 243, 244));
        jPanel2.add(lblPacienteID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 100, 30));

        lblPacienteRaza1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPacienteRaza1.setForeground(new java.awt.Color(242, 243, 244));
        jPanel2.add(lblPacienteRaza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 180, 30));

        lblPacienteTam1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPacienteTam1.setForeground(new java.awt.Color(242, 243, 244));
        jPanel2.add(lblPacienteTam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 170, 30));

        separador1.setBackground(new java.awt.Color(24, 212, 163));
        separador1.setForeground(new java.awt.Color(24, 212, 163));
        jPanel2.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 230, -1));

        lblPacienteDue2.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPacienteDue2.setForeground(new java.awt.Color(242, 243, 244));
        jPanel2.add(lblPacienteDue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 200, 30));

        lblPacienteTam2.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPacienteTam2.setForeground(new java.awt.Color(242, 243, 244));
        jPanel2.add(lblPacienteTam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 170, 30));

        lblPacienteRaza2.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPacienteRaza2.setForeground(new java.awt.Color(242, 243, 244));
        jPanel2.add(lblPacienteRaza2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 160, 30));

        lblPacienteTam3.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPacienteTam3.setForeground(new java.awt.Color(242, 243, 244));
        jPanel2.add(lblPacienteTam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 170, 30));

        lblPacienteRaza3.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPacienteRaza3.setForeground(new java.awt.Color(242, 243, 244));
        jPanel2.add(lblPacienteRaza3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 160, 30));

        lblPacienteDue3.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPacienteDue3.setForeground(new java.awt.Color(242, 243, 244));
        jPanel2.add(lblPacienteDue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 200, 20));

        separador2.setBackground(new java.awt.Color(24, 212, 163));
        separador2.setForeground(new java.awt.Color(24, 212, 163));
        jPanel2.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 230, -1));

        lblPacienteNombre1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPacienteNombre1.setForeground(new java.awt.Color(242, 243, 244));
        jPanel2.add(lblPacienteNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 140, 30));

        lblPacienteNombre2.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPacienteNombre2.setForeground(new java.awt.Color(242, 243, 244));
        jPanel2.add(lblPacienteNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 140, 30));

        lblPacienteID2.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPacienteID2.setForeground(new java.awt.Color(242, 243, 244));
        jPanel2.add(lblPacienteID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 100, 30));

        lblPacienteNombre3.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPacienteNombre3.setForeground(new java.awt.Color(242, 243, 244));
        jPanel2.add(lblPacienteNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 150, 30));

        lblPacienteID3.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPacienteID3.setForeground(new java.awt.Color(242, 243, 244));
        jPanel2.add(lblPacienteID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 110, 30));

        lblCosto3.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblCosto3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblCosto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 80, 30));

        lblCosto1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblCosto1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblCosto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 80, 30));

        lblCosto2.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblCosto2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblCosto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 80, 30));

        lblTotal1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblTotal1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        lblTotal3.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblTotal3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblTotal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        lblTotal2.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblTotal2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        lblAumento3.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblAumento3.setForeground(new java.awt.Color(249, 77, 0));
        jPanel2.add(lblAumento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        lblAumento1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblAumento1.setForeground(new java.awt.Color(249, 77, 0));
        jPanel2.add(lblAumento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        lblAumento2.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblAumento2.setForeground(new java.awt.Color(249, 77, 0));
        jPanel2.add(lblAumento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 360, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazaActionPerformed

    private void txtNombreDueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDueActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectActionPerformed
    int cont = 0;
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
            lblPacienteID1.setText("");
            lblPacienteNombre1.setText("");
            lblPacienteRaza1.setText("");
            lblPacienteTam1.setText("");
            lblPacienteDue1.setText("");
            lblCosto1.setText("");
            lblTotal1.setText("");
            lblAumento1.setText("");
            
            lblPacienteID2.setText("");
            lblPacienteNombre2.setText("");
            lblPacienteRaza2.setText("");
            lblPacienteTam2.setText("");
            lblPacienteDue2.setText("");
            lblCosto2.setText("");
            lblTotal2.setText("");
            lblAumento2.setText("");
            
            lblPacienteID3.setText("");
            lblPacienteNombre3.setText("");
            lblPacienteRaza3.setText("");
            lblPacienteTam3.setText("");
            lblPacienteDue3.setText("");
            lblCosto3.setText("");
            lblTotal3.setText("");
            lblAumento3.setText("");
            
            btnLimpiar.setVisible(false);
            btnAgregar.setVisible(true);
            separador1.setVisible(false);
            separador2.setVisible(false);
            cont = 0;
            
            txtId.setText("0005");
            jPanel2.setBackground(Color.decode("#222c42"));
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        String id = txtId.getText(); 
        String nombre = txtNombre.getText();
        String raza = txtRaza.getText();        
        String dimension = (String) select.getSelectedItem();
        String nombreDue = txtNombreDue.getText();
        String motivo = (String) selectCosto.getSelectedItem();
        
       boolean validacion = validacionForm(nombre,raza,nombreDue);
       if(validacion){
            
            double costo = 0.0;
            jPanel2.setBackground(Color.decode("#181f2f"));
            
            cont++;
            if (cont == 1){
                Paciente paciente = new Paciente(id,nombre,raza,dimension,nombreDue);            
                lblPacienteID1.setText("ID: " + paciente.obtenerId());
                lblPacienteNombre1.setText("Nombre: " + paciente.obtenerNombre());
                lblPacienteRaza1.setText("Raza: " + paciente.obtenerRaza());
                lblPacienteTam1.setText("Tamaño: " + paciente.obtenerDimension());
                lblPacienteDue1.setText("Dueño: " + paciente.obtenerNombreDue());
                txtId.setText(txtId.getText().substring(0,txtId.getText().length()-1)+6);
                vaciarCampos();
                separador1.setVisible(true);            


                switch(motivo){
                    case "consulta":
                        lblCosto1.setText("Costo: $2500");
                        costo = 2500;
                        break;
                    case "baño":
                        lblCosto1.setText("Costo: $1000");
                        costo = 1000;
                        break;
                    case "corte de pelo":
                        lblCosto1.setText("Costo: $1300");
                        costo = 1300;
                        break;
                    default:
                        lblCosto1.setText("");
                        break;
            }
            establecerDescuento(lblAumento1,dimension);
            lblTotal1.setText("Total: $"+ paciente.calcularCosto(costo));
            }
            else if (cont == 2){
                Paciente paciente2 = new Paciente(id,nombre,raza,dimension,nombreDue);
                lblPacienteID2.setText("ID: " + paciente2.obtenerId());
                lblPacienteNombre2.setText("Nombre: " + paciente2.obtenerNombre());
                lblPacienteRaza2.setText("Raza: " + paciente2.obtenerRaza());
                lblPacienteTam2.setText("Tamaño: " + paciente2.obtenerDimension());
                lblPacienteDue2.setText("Dueño: " + paciente2.obtenerNombreDue());
                txtId.setText(txtId.getText().substring(0,txtId.getText().length()-1)+7);
                vaciarCampos();
                separador2.setVisible(true);

                switch(motivo){
                    case "consulta":
                        lblCosto2.setText("Costo: $2500");
                        costo = 2500;
                        break;
                    case "baño":
                        lblCosto2.setText("Costo: $1000");
                        costo = 1000;
                        break;
                    case "corte de pelo":
                        lblCosto2.setText("Costo: $1300");
                        costo = 1300;
                        break;
                    default:
                        lblCosto2.setText("");
                        break;
                }
                establecerDescuento(lblAumento2,dimension);
                lblTotal2.setText("Total: $"+ paciente2.calcularCosto(costo));
            }
            else if(cont == 3){
                Paciente paciente3 = new Paciente(id,nombre,raza,dimension,nombreDue);
                 lblPacienteID3.setText("ID: " + paciente3.obtenerId());
                lblPacienteNombre3.setText("Nombre: " + paciente3.obtenerNombre());
                lblPacienteRaza3.setText("Raza: " + paciente3.obtenerRaza());
                lblPacienteTam3.setText("Tamaño: " + paciente3.obtenerDimension());
                lblPacienteDue3.setText("Dueño: " + paciente3.obtenerNombreDue());

                switch(motivo){
                    case "consulta":
                        lblCosto3.setText("Costo: $2500");
                        costo = 2500;
                        break;
                    case "baño":
                        lblCosto3.setText("Costo: $1000");
                        costo = 1000;
                        break;
                    case "corte de pelo":
                        lblCosto3.setText("Costo: $1300");
                        costo = 1300;
                        break;
                    default:
                        lblCosto3.setText("");
                        break;
                }
                establecerDescuento(lblAumento3,dimension);
                lblTotal3.setText("Total: $"+ paciente3.calcularCosto(costo));
                vaciarCampos();
                txtId.setText("");
                btnAgregar.setVisible(false);
                btnLimpiar.setVisible(true);
            }
           }
             
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void selectCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectCostoActionPerformed
    public void vaciarCampos(){            
            txtNombre.setText("");
            txtRaza.setText("");
            txtNombreDue.setText("");
    }
    
    public void establecerDescuento(JLabel lbl,String dimension){
       switch (dimension) {
            case "grande":                
                lbl.setText("El aumento es de un 30%");
                break;
            case "mediano":                
                lbl.setText("El aumento es de un 20%");
                break;
            default:                
                lbl.setText("El aumento es de un 10%");
                break;
        }
    }
    
    public boolean validacionForm(String nombre, String raza, String nombreDue){
        boolean formVal;
        if (!nombre.equals("") && !raza.equals("") && !nombreDue.equals("")){
            validationNombre.setText("");
            separadorNombre.setBackground(Color.decode("#18d4a3"));
            validationRaza.setText("");
            separadorRaza.setBackground(Color.decode("#18d4a3"));
            validationNomDue.setText("");
            separadorNombreDue.setBackground(Color.decode("#18d4a3"));
            formVal=true;
        }
        else if(nombre.equals("")){
            validationNombre.setText("•");
            separadorNombre.setBackground(Color.decode("#ef3038"));
            formVal=false;
        }
        else if(raza.equals("")){
            validationRaza.setText("•");
            separadorRaza.setBackground(Color.decode("#ef3038"));
            formVal = false;            
        }
        else{
            validationNomDue.setText("•");
            separadorNombreDue.setBackground(Color.decode("#ef3038"));
            formVal = false;
        }
        return formVal;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel img;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAumento1;
    private javax.swing.JLabel lblAumento2;
    private javax.swing.JLabel lblAumento3;
    private javax.swing.JLabel lblCosto1;
    private javax.swing.JLabel lblCosto2;
    private javax.swing.JLabel lblCosto3;
    private javax.swing.JLabel lblDimension;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblListado;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreDue;
    private javax.swing.JLabel lblPacienteDue1;
    private javax.swing.JLabel lblPacienteDue2;
    private javax.swing.JLabel lblPacienteDue3;
    private javax.swing.JLabel lblPacienteID1;
    private javax.swing.JLabel lblPacienteID2;
    private javax.swing.JLabel lblPacienteID3;
    private javax.swing.JLabel lblPacienteNombre1;
    private javax.swing.JLabel lblPacienteNombre2;
    private javax.swing.JLabel lblPacienteNombre3;
    private javax.swing.JLabel lblPacienteRaza1;
    private javax.swing.JLabel lblPacienteRaza2;
    private javax.swing.JLabel lblPacienteRaza3;
    private javax.swing.JLabel lblPacienteTam1;
    private javax.swing.JLabel lblPacienteTam2;
    private javax.swing.JLabel lblPacienteTam3;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblTotal2;
    private javax.swing.JLabel lblTotal3;
    private javax.swing.JComboBox<String> select;
    private javax.swing.JComboBox<String> selectCosto;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separadorNombre;
    private javax.swing.JSeparator separadorNombreDue;
    private javax.swing.JSeparator separadorRaza;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreDue;
    private javax.swing.JTextField txtRaza;
    private javax.swing.JLabel validationNomDue;
    private javax.swing.JLabel validationNombre;
    private javax.swing.JLabel validationRaza;
    // End of variables declaration//GEN-END:variables
}
